<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    
    <link rel="stylesheet" href="css/estilo.css">
    <script src="js/script.js"></script></head>

	<body>
        <header><!-- inicio Cabecalho -->
            <nav id="itens" class="navbar navbar-expand-lg navbar-light bg-light">
              <img class="icon" src="img/cao.png" width="40">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars text-black"></i>
              </button>
              <div class="collapse navbar-collapse d-flex justify-content-around" id="navbarNavDropdown">
                <ul class="navbar-nav ">
                  <li class="nav-item ">
                    <a class="nav-link" href="/">Home </a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="/servicos">Serviços<span class="sr-only">(current)</span></a>
                  </li>
				  <li class="nav-item">
				  	<a class="nav-link" href="/nova_tarefa">Marcar Horário</a>
				  </li>
				  <li class="nav-item">
				  	<a class="nav-link" href="/todas_tarefas">Meus Agendamentos</a>
				  </li>
				  <li class="nav-item">
				  	<a class="nav-link" href="/sair">sair</a>
				  </li>
                  
                </ul>
              </div>
            </nav>
            </header><!--/fim Cabecalho -->
            
		<div class="container app">
			<div class="row">
				<div class="col-md-3 menu">
					<ul class="list-group">
						<li class="list-group-item"><a href="/nova_tarefa">Marcar Horário</a></li>
						<li class="list-group-item"><a href="/todas_tarefas">Meus Agendamentos</a></li>
						<li class="list-group-item"><a href="/sair">sair</a></li>
					</ul>
				</div>

				<div class="col-md-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4>Tarefas pendentes</h4>
								<hr/>

								<div class="row mb-3 d-flex align-items-center tarefa">
									<div class="col-sm-9">Lavar o carro</div>
									<div class="col-sm-3 mt-2 d-flex justify-content-between">
										<i class="fas fa-trash-alt fa-lg text-danger"></i>
										<i class="fas fa-edit fa-lg text-info"></i>
										<i class="fas fa-check-square fa-lg text-success"></i>
									</div>
								</div>

								<div class="row mb-3 d-flex align-items-center tarefa">
									<div class="col-sm-9">Passear com o cachorro</div>
									<div class="col-sm-3 mt-2 d-flex justify-content-between">
										<i class="fas fa-trash-alt fa-lg text-danger"></i>
										<i class="fas fa-edit fa-lg text-info"></i>
										<i class="fas fa-check-square fa-lg text-success"></i>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>