<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    
    <link rel="stylesheet" href="css/estilo.css">
	<script src="js/script.js"></script>

	<style>
		 .servicos{
			font-family: 'Coiny', cursive;
			color:#fda8a8e5 ;
			font-size:30px;
			text-emphasis: center;
			text-align: center;
			text-transform: uppercase;
			margin-bottom: auto;
			
		 }

		 
		 .btn{
			width: 100%;
			height: 50px;
			background-color: white;
			border:2px solid #fdc1c1;
			font-family: 'Poppins', sans-serif;
			color:#434343d8;
			font-size:1.5em;
			margin-top: 2%;
			box-shadow:0 0 8px #fdc1c1 ;
		  }
	
		  button:hover{
			  background-color:#fdc1c1 ;
			  
			  box-shadow:5px 5px 20px #fdbaba ;
		  }

		 .form-group{
			width: auto;
			display: flex;
			align-items: center;
			align-content: center;
		  }
		  .custom-checkbox{
			  width: auto;
		  }

		  label{
			width: 155px;
			height: 50px;
			padding-top: 2.4%;
			
		  }

		  fieldset{
			border: 1px solid #43434386;
			padding: 15px 15px 15px 15px;
			width: 550px;
			display:table-cell; 
			width: 100%;
			border-radius: 5px;
			
		  }

		  input,textarea,select,option {
			font-family: 'Poppins', sans-serif;
			padding-left: 5%;
			padding-right: 5%;
			color:#434343c2;
			font-size:20px;
			padding-left: 5%;
			padding-right: 5%;
			box-shadow:0 0 8px #fdc1c1 ;
		  }

		  .cadastro{
			background-color: white;
			padding: 40px 70px 70px 70px;
			border-radius: 5px;
			width: auto;
		  
		 }

		 legend{
			width: auto;
			margin-left:16%;
			text-align: center;
		  }

		.area-servicos{
			margin: auto;
			width: 65%;
			margin-bottom: 4%;
			display: flex;
			align-items: center;
			align-content: space-between;
			
		}
		
	</style>

</head>

	<body>
        <header><!-- inicio Cabecalho -->
            <nav id="itens" class="navbar navbar-expand-lg navbar-light bg-light">
              <img class="icon" src="img/cao.png" width="40">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars text-black"></i>
              </button>
              <div class="collapse navbar-collapse d-flex justify-content-around" id="navbarNavDropdown">
                <ul class="navbar-nav ">
                  <li class="nav-item ">
                    <a class="nav-link" href="/">Home </a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="/agendamentos">Serviços</a>
                  </li>
				  <li class="nav-item">
				  	<a class="nav-link" href="/nova_tarefa">Marcar Horário<span class="sr-only">(current)</span></a>
				  </li>
				  <li class="nav-item">
				  	<a class="nav-link" href="/sair">sair</a>
				  </li>
                </ul>
              </div>
            </nav>
            </header><!--/fim Cabecalho -->
            
		<div class="container app">
			<div class="row" >
		
				<div class="col-md-12">
					<div class="container cadastro">
						<div class="row">
							<div class="col">
								<h3 class="servicos">Agendamento de Serviços</h3>
								<hr >

								<form>
									<fieldset>
                
										<legend > Informações do pet </legend>
										<div class="form-group col-md">
										  <label for="nome">Nome do pet </label>
										  <input  type="nome" class="form-control" id="nome" placeholder="Nome" >
										</div>
						  
										<div class="form-group col-md">
										  <label for="tipo-animal">Meu pet é um(a)</label>
										  <select type="text" class="form-control" name="tipo-animal" id="tipo-animal">
											  <option value="">----</option>
											  <option value="1">um(a) gatinho(a)</option>
											  <option value="2">um(a) cachorrinho(a)</option>
										  </select>
										</div>
									  
										<div class="form-group col-md">
											<label for="info"> Observações importantes? </label>
											<textarea  class="form-control" name="info" id="info" rows="3"></textarea>
										</div>
						
										
									  </fieldset>

									  <fieldset>
                
										<legend> Escolha um Serviço </legend>

										<form>
											<div class="form-row  area-servicos">

												<div class="container custom-control custom-checkbox">Pet Sitting
													<input type="checkbox" id="op-pet-sitting">
													<span class="checkmark"></span>
												</div>	
											  <div class="container col-auto opcao">
												<select type="text" class="form-control" id="opcao">
												  <option selected>------</option>
												  <option value="20">Plano Diário  (R$20)</option>
												  <option value="50">Plano Horário (R$50)</option>
												</select>
											  </div>
											</div>

											<div class="form-row  area-servicos">

												<div class="container custom-control custom-checkbox">Pet Hotel
													<input type="checkbox" id="op-pet-hotel">
													<span class="checkmark"></span>
												</div>	
											  <div class="container col-auto opcao">
												<select type="text" class="form-control" id="opcao">
												  <option selected>------</option>
												  <option value="40">Plano Diário  (R$40)</option>
												  <option value="65">Plano Semanal (R$65)</option>
												  <option value="110">Plano Mensal  (R$110)</option>
												</select>
											  </div>
											</div>

											<div class="form-row align-items-center area-servicos">

												<div class="container custom-control custom-checkbox">Petcure
													<input type="checkbox" id="op-petcure">
													<span class="checkmark"></span>
												</div>	
											  <div class="container col-auto opcao" >
												<select type="text" class="form-control" id="opcao">
												  <option selected>------</option>
												  <option value="40">Plano Básico (R$40)</option>
												  <option value="65">Plano Chique (R$65)</option>
												  <option value="80">Plano Diva   (R$80)</option>
												</select>
											  </div>
											</div>

											<div class="form-row align-items-center area-servicos">

													
												<div class="container custom-control custom-checkbox">Acampamento
													<input type="checkbox" id="op-acampamento" disabled>
													<span class="checkmark"></span>
												</div>
											  <div class="container col-auto opcao" >
												<select type="text" class="form-control" id="opcao" disabled>
												  <option selected>------</option>
												  <option value="20">Dia de Semana (R$20)</option>
												  <option value="35">Fim de Semana (R$35)</option>
												</select>
												
											  </div>

											</div>
											
										</form>
									  </fieldset>

									  <fieldset>
                
										<legend > Informações finais </legend>

										<form>
											<div class="form-group col-md">
												<label for="data">Data do Agendamento </label>
												<input type="date" class="form-control" id="data" >
											</div>

											<div class="form-group col-md">
												<label for="hora">Horário </label>
												<input type="time" class="form-control" id="hora" >
												
											</div>
											<small>*Funcionamos das 9:00 às 18:00</small>
										</form>
									  </fieldset>

									<button class="btn">Cadastrar</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>