<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    
  <!-- Meta tags Obrigatórias -->
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

  <link rel="stylesheet" href="css/estilo.css">

  <title>CADASTRO CONCLUÍDO</title>

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Coiny&family=Poppins:wght@300&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap');
    img{
      height: 10%;
    }

    h2{
      font-family: 'Coiny', cursive;
      color:#249ab4;
      font-size:28px;
      text-emphasis: center;
      text-align: center;
      
      height: 100px;
    }
    
		 .btn{
			width: 100%;
			height: 50px;
			background-color: white;
			border:2px solid #fdc1c1;
			font-family: 'Poppins', sans-serif;
			color:#434343b4;
			font-size:1.5em;
			margin-top: 2%;
			box-shadow:0 0 8px #fdc1c1 ;
		  }
	
		  button:hover{
			  background-color:#fdc1c1 ;
			  
			  box-shadow:5px 5px 20px #fdbaba ;
      }
      container{
        width: auto;
      }
  </style>

</head>
<body>

  <div class="container">
    <div class="d-flex justify-content-center mt-5">
      <div class="" >
        <div class="">

          <div class="d-flex justify-content-center">
            <img src="/img/dog6.jpg">
          </div>

          <div class="row">
            <div class="col">
              <h2>Cadastro realizado com sucesso !</h2>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <button href="/login" class="btn btn-block">Clique aqui para fazer login!</button>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>


</body>
</html>
    
  