<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <script src="js/script.js"></script>

    <title>INSCREVA-SE</title>
    <style>
      .formulario{
        display: flex;
        justify-content: center;
        align-items: center;
      }
      body{
        background: url(img/dog-blue.png);
        background-repeat: no-repeat;
        background-size: 100%;
        opacity: 90%;
        border: 1ps solid red;
        /*backdrop-filter: blur(2px);*/
      }

      #login{
        margin: 10%;
        background-color: white;
        border: #d5d7d8;
        border-style:unset groove;
        padding: 60px 60px 60px 60px; 
        width: 400px;
        border-radius: 4px;
      }

      form>div{
        padding-top: 10px ;
        padding-bottom: 10px ;
      }
      .textarea{
        box-sizing: border-box;
        border: none;
        width: 100%;
        height: 50px;
        background-color: rgba(195, 195, 195, 0.685);
        color: white;
        border-radius: 3px;
      }

      .icon{
        width: 25%;
        margin-left: 40%;
        margin-bottom: 30px;
      }

      button{
        width: 100%;
        height: 50px;
        background-color: #249ab4;
        font-family: 'Poppins', sans-serif;
        color:white;
        font-size:20px;
      }

      button:hover{
        background-color: #249ab4bd;
      }

      input {
        font-family: 'Poppins', sans-serif;
        color:#434343c2;
        font-size:20px;
        padding-left: 5%;
      }

    </style>
</head>
<body>
    

      <div class="formulario container" >
         
           <div id="login" class="row" >
            
            <form method="post" action="/autenticar">
              
              <img class="icon" src="img/cao.png" width="40">

              <div class="container-row">
                <input class="textarea" name="email" type="email" class="form-control form-control-lg" id="email" placeholder="Email" >
              </div>

              <div class="container-row ">
                <input class="textarea" name="senha" type="password" class="form-control form-control-lg" id="senha" placeholder="Senha">
              </div>

              <div id="submit" >
                <button  type="submit" aria-describedby="submitHelp" class="btn">
                  ENTRAR
              </div>

              <?php if($this->view->login == 'erro') { ?>
                <div class="row">
                  <div class="col">
                    <span class="text text-danger">*E-mail e ou senha inválido(s)</span>
                  </div>
                </div>
              <?php } ?>

              <small id="submitHelp" class="form-text text-muted'">
                ainda não faz parte da nossa familia? então clique aqui e <a href="/inscreverse"> cadastre-se !</a>
              </small>

              

           </form>
          
        </div>
           </div>

      </div>

      
      





      <!-- JavaScript (Opcional) -->
      <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      
</body>
</html>